language: rust
rust:
  - stable
os:
  - linux
  - osx
  - windows
before_install:
  - rustup component add clippy
script:
  - cargo clippy --all-targets --all-features --verbose -- -D warnings
  - cargo test --verbose
notifications:
    email: false
