[package]
authors = ["EFanZh <efanzh@gmail.com>"]
edition = "2024"
name = "leet-code"
publish = false
version = "0.1.0"

[workspace]
members = ["tools/check-cpp-code-format", "tools/progress-tracker", "xtask"]

[workspace.lints.rust]
ambiguous_negative_literals = { level = "warn", priority = 1 }
closure_returning_async_block = { level = "warn", priority = 1 }
explicit_outlives_requirements = { level = "warn", priority = 1 }
impl_trait_redundant_captures = { level = "warn", priority = 1 }
let_underscore_drop = { level = "warn", priority = 1 }
macro_use_extern_crate = { level = "warn", priority = 1 }
meta_variable_misuse = { level = "warn", priority = 1 }
missing_abi = { level = "warn", priority = 1 }
missing_docs = { level = "warn", priority = 1 }
redundant_imports = { level = "warn", priority = 1 }
redundant_lifetimes = { level = "warn", priority = 1 }
single_use_lifetimes = { level = "warn", priority = 1 }
trivial_casts = { level = "warn", priority = 1 }
trivial_numeric_casts = { level = "warn", priority = 1 }
unit_bindings = { level = "warn", priority = 1 }
unnameable_types = { level = "warn", priority = 1 }
unsafe_code = { level = "warn", priority = 1 }
unused_crate_dependencies = { level = "warn", priority = 1 }
unused_extern_crates = { level = "warn", priority = 1 }
unused_import_braces = { level = "warn", priority = 1 }
unused_lifetimes = { level = "warn", priority = 1 }
unused_macro_rules = { level = "warn", priority = 1 }
unused_qualifications = { level = "warn", priority = 1 }
variant_size_differences = { level = "warn", priority = 1 }

[workspace.lints.clippy]
alloc_instead_of_core = { level = "warn", priority = 1 }
allow_attributes = { level = "warn", priority = 1 }
allow_attributes_without_reason = { level = "warn", priority = 1 }
as_conversions = { level = "warn", priority = 1 }
assertions_on_result_states = { level = "warn", priority = 1 }
cargo = "warn"
cfg_not_test = { level = "warn", priority = 1 }
clone_on_ref_ptr = { level = "warn", priority = 1 }
dbg_macro = { level = "warn", priority = 1 }
deref_by_slicing = { level = "warn", priority = 1 }
empty_drop = { level = "warn", priority = 1 }
empty_enum_variants_with_brackets = { level = "warn", priority = 1 }
empty_structs_with_brackets = { level = "warn", priority = 1 }
field_scoped_visibility_modifiers = { level = "warn", priority = 1 }
format_push_string = { level = "warn", priority = 1 }
get_unwrap = { level = "warn", priority = 1 }
if_then_some_else_none = { level = "warn", priority = 1 }
infinite_loop = { level = "warn", priority = 1 }
lossy_float_literal = { level = "warn", priority = 1 }
multiple_crate_versions = { level = "allow", priority = 1 }
mutex_atomic = { level = "warn", priority = 1 }
non_zero_suggestions = { level = "warn", priority = 1 }
nursery = "warn"
panic_in_result_fn = { level = "warn", priority = 1 }
pedantic = "warn"
print_stderr = { level = "warn", priority = 1 }
print_stdout = { level = "warn", priority = 1 }
rc_buffer = { level = "warn", priority = 1 }
rc_mutex = { level = "warn", priority = 1 }
redundant_type_annotations = { level = "warn", priority = 1 }
renamed_function_params = { level = "warn", priority = 1 }
rest_pat_in_fully_bound_structs = { level = "warn", priority = 1 }
same_name_method = { level = "warn", priority = 1 }
self_named_module_files = { level = "warn", priority = 1 }
shadow_unrelated = { level = "warn", priority = 1 }
string_lit_chars_any = { level = "warn", priority = 1 }
tests_outside_test_module = { level = "warn", priority = 1 }
todo = { level = "warn", priority = 1 }
try_err = { level = "warn", priority = 1 }
undocumented_unsafe_blocks = { level = "warn", priority = 1 }
unimplemented = { level = "warn", priority = 1 }
unnecessary_safety_comment = { level = "warn", priority = 1 }
unnecessary_safety_doc = { level = "warn", priority = 1 }
unnecessary_self_imports = { level = "warn", priority = 1 }
unneeded_field_pattern = { level = "warn", priority = 1 }
unseparated_literal_suffix = { level = "warn", priority = 1 }
use_debug = { level = "warn", priority = 1 }
verbose_file_reads = { level = "warn", priority = 1 }
wildcard_dependencies = { level = "allow", priority = 1 }            # Project specific.

[lints]
workspace = true

[dependencies]
rand = "0.8"

[dev-dependencies]
approx = "*"
