[package]
authors = ["EFanZh <efanzh@gmail.com>"]
edition = "2018"
name = "xtask"
version = "0.1.0"

[dependencies]
lazy_static = "*"
serde_json = "*"
structopt = "*"
tempfile = "*"
which = "*"

[target.'cfg(target_os="windows")'.dependencies]
cc = "*"
