[package]
authors = ["EFanZh <efanzh@gmail.com>"]
edition = "2018"
name = "progress-tracker"
version = "0.1.0"

[dependencies]
chrono = "*"
git2 = "*"
plotters = "*"
reqwest = {version = "*", features = ["blocking", "json"]}
serde = {version = "*", features = ["derive"]}
serde_json = "*"
