on: push
jobs:
    check-code-format:
        runs-on: ubuntu-latest
        steps:
          - uses: actions/checkout@v2
          - uses: actions-rs/toolchain@v1
          - run: cargo run --manifest-path=ci/check-cpp-code-format/Cargo.toml c++
    tests:
        runs-on: ${{ matrix.os }}
        steps:
          - uses: actions/checkout@v2
          - run: vcpkg install gtest
          - run: cmake -S c++ -B build -D CMAKE_TOOLCHAIN_FILE="$VCPKG_INSTALLATION_ROOT/scripts/buildsystems/vcpkg.cmake"
          - run: cmake --build build
          - run: ctest
            working-directory: build
        strategy:
            matrix:
                os:
                  - macOS-latest
                  - ubuntu-latest
    tests-windows:
        runs-on: windows-latest
        steps:
          - uses: actions/checkout@v2
          - run: vcpkg install gtest --triplet ${{ matrix.platform }}-windows
          - run: >-
                cmake
                -S c++
                -B build
                -A $('${{ matrix.platform }}' -eq 'x64' ? 'x64' : 'Win32')
                -D CMAKE_TOOLCHAIN_FILE="$env:VCPKG_INSTALLATION_ROOT\scripts\buildsystems\vcpkg.cmake"
          - run: cmake --build build
          - run: ctest
            working-directory: build
        strategy:
            matrix:
                platform:
                  - x64
                  - x86
