on: push
jobs:
    rustfmt:
        runs-on: ${{ matrix.os }}
        steps:
          - uses: actions-rs/toolchain@v1
            with:
                components: rustfmt
          - uses: actions/checkout@v2
          - run: cargo fmt -- --check
        strategy:
            matrix:
                os:
                  - macOS-latest
                  - ubuntu-latest
                  - windows-latest
    clippy:
        runs-on: ${{ matrix.os }}
        steps:
          - uses: actions-rs/toolchain@v1
            with:
                components: clippy
          - uses: actions/checkout@v2
          - run: cargo clippy --all-targets --all-features -- -W clippy::pedantic -A clippy::cast-possible-truncation -A clippy::cast-possible-wrap -A clippy::cast-precision-loss -A clippy::cast-sign-loss -A clippy::must-use-candidate -A clippy::needless-pass-by-value -A clippy::non-ascii-literal -D warnings
        strategy:
            matrix:
                os:
                  - macOS-latest
                  - ubuntu-latest
                  - windows-latest
    tests:
        runs-on: ${{ matrix.os }}
        steps:
          - uses: actions-rs/toolchain@v1
          - uses: actions/checkout@v2
          - run: cargo test
        strategy:
            matrix:
                os:
                  - macOS-latest
                  - ubuntu-latest
                  - windows-latest
    coverage:
        runs-on: ubuntu-latest
        steps:
          - uses: actions-rs/toolchain@v1
            with:
                toolchain: nightly
                override: true
                components: llvm-tools-preview
          - run: cargo install cargo-binutils rustfilt
          - uses: actions/checkout@v2
          - run: cargo test
            env:
                RUSTFLAGS: -Zinstrument-coverage
          - run: cargo profdata -- merge --output default.profdata --sparse default.profraw
          - run: cargo cov -- export --ignore-filename-regex '^/' --format lcov -Xdemangler rustfilt --instr-profile default.profdata target/debug/deps/leet_code-???????????????? > lcov.info
          - uses: coverallsapp/github-action@master
            with:
                github-token: ${{ secrets.GITHUB_TOKEN }}
                path-to-lcov: lcov.info
    update-progress:
        runs-on: ubuntu-latest
        steps:
          - uses: actions-rs/toolchain@v1
          - uses: actions/checkout@v2
          - run: git fetch --prune --unshallow
          - run: cargo run --package progress-tracker -- . progress-report
          - uses: peaceiris/actions-gh-pages@v3
            with:
                github_token: ${{ secrets.GITHUB_TOKEN }}
                publish_dir: progress-report
