on: push
jobs:
    rustfmt:
        runs-on: ${{ matrix.os }}
        steps:
          - uses: actions/checkout@v2
          - uses: actions-rs/toolchain@v1
            with:
                toolchain: stable
                components: rustfmt
          - run: cargo fmt -- --check
        strategy:
            matrix:
                os:
                  - macOS-latest
                  - ubuntu-latest
                  - windows-latest
    clippy:
        runs-on: ${{ matrix.os }}
        steps:
          - uses: actions/checkout@v2
          - uses: actions-rs/toolchain@v1
            with:
                toolchain: stable
                components: clippy
          - run: cargo clippy --all-targets --all-features -- -W clippy::pedantic -A clippy::module-name-repetitions -A clippy::must-use-candidate -A clippy::cast-precision-loss -A clippy::non-ascii-literal -A clippy::cast-possible-truncation -A clippy::cast-possible-wrap -A clippy::cast-sign-loss -A clippy::needless-pass-by-value -D warnings
        strategy:
            matrix:
                os:
                  - macOS-latest
                  - ubuntu-latest
                  - windows-latest
    tests:
        runs-on: ${{ matrix.os }}
        steps:
          - uses: actions/checkout@v2
          - uses: actions-rs/toolchain@v1
            with:
                toolchain: stable
          - run: cargo test
        strategy:
            matrix:
                os:
                  - macOS-latest
                  - ubuntu-latest
                  - windows-latest
    update-progress:
        runs-on: ubuntu-latest
        steps:
          - uses: actions/checkout@v2
          - run: git fetch --prune --unshallow
          - uses: actions-rs/toolchain@v1
            with:
                toolchain: stable
          - run: cargo run --package progress-tracker -- . progress-report
          - uses: peaceiris/actions-gh-pages@v3
            with:
                github_token: ${{ secrets.GITHUB_TOKEN }}
                publish_dir: progress-report
