name: Coverage
on:
    push:
        branches:
          - master
jobs:
    coverage:
        runs-on: ubuntu-latest
        steps:
          - uses: actions/checkout@v4
          - run: rustup update
          - run: rustup component add llvm-tools
          - run: sudo apt-get install --no-install-recommends -y ninja-build
          - run: vcpkg install gtest
          - run: >-
                cargo xtask coverage
                --cmake-toolchain-file "$VCPKG_INSTALLATION_ROOT/scripts/buildsystems/vcpkg.cmake"
                --llvm-version 18
                -o coverage/lcov.info
          - uses: codecov/codecov-action@v5
            with:
                files: coverage/lcov.info
          - uses: coverallsapp/github-action@v2
            with:
                github-token: ${{ secrets.GITHUB_TOKEN }}
