on: push
jobs:
    coverage:
        runs-on: ubuntu-20.04
        steps:
          - uses: actions/checkout@v2
          - run: vcpkg install gtest
          - uses: actions-rs/toolchain@v1
            with:
                toolchain: nightly
                override: true
                components: llvm-tools-preview
          - uses: actions-rs/install@v0.1
            with:
                crate: grcov
                use-tool-cache: true
          - run: >-
                cargo xtask coverage
                --cmake-toolchain-file "$VCPKG_INSTALLATION_ROOT/scripts/buildsystems/vcpkg.cmake"
                -o coverage/lcov.info
          - uses: codecov/codecov-action@v1
            with:
                file: coverage/lcov.info
          - uses: coverallsapp/github-action@master
            with:
                github-token: ${{ secrets.GITHUB_TOKEN }}
